import "@/styles/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { PropsWithChildren } from "react";

export const metadata: Metadata = {
  title: "Mayoblox | Test Assesment Panya Store",
  description: "Generated by create next app",
};

const chillax = localFont({
  src: "../public/fonts/Chillax-Variable.woff2",
  variable: "--font-chillax",
  weight: "100 900",
});

const jakartaSans = localFont({
  src: "../public/fonts/PlusJakartaSans-Variable.woff2",
  variable: "--font-jakarta-sans",
  weight: "100 900",
});

const cherryBombOne = localFont({
  src: "../public/fonts/CherryBombOne-Regular.woff2",
  variable: "--font-cherry-bomb",
  weight: "400",
});

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className="">
      <body
        className={`antialiased ${chillax.variable} ${jakartaSans.variable} ${cherryBombOne.variable} font-jakarta-sans max-w-[1920px] mx-auto`}
      >
        {children}
      </body>
    </html>
  );
}
